import { hashSync } from 'bcrypt-ts-edge';

const now = new Date();

const sampleData = {
  users: [
    {
      name: 'John Admin',
      firstName: 'John',
      lastName: 'Admin',
      email: 'admin@example.com',
      password: hashSync('password', 10),
      role: 'admin',
      bio: 'E-commerce platform administrator with 5+ years of experience.',
      dateOfBirth: new Date('1985-03-15'),
      phone: '+1-555-0123',
      gender: 'male',
      country: 'United States',
      state: 'California',
      city: 'San Francisco',
      zipCode: '94102',
      website: 'https://johnadmin.com',
      linkedIn: 'https://linkedin.com/in/johnadmin',
      occupation: 'System Administrator',
      company: 'Reware Thrift Commerce',
      newsletter: true,
      smsUpdates: true,
      language: 'en',
      timezone: 'America/Los_Angeles',
      currency: 'USD',
      isVerified: true,
      isActive: true,
      lastLoginAt: new Date(),
    },
    {
      name: 'Jane Smith',
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'user@example.com',
      password: hashSync('password', 10),
      role: 'user',
      bio: 'Fashion enthusiast and sustainable shopping advocate.',
      dateOfBirth: new Date('1992-07-22'),
      phone: '+1-555-0456',
      gender: 'female',
      country: 'United States',
      state: 'New York',
      city: 'New York',
      zipCode: '10001',
      instagram: 'https://instagram.com/janesmith',
      twitter: 'https://twitter.com/janesmith',
      occupation: 'Marketing Specialist',
      company: 'Fashion Forward Inc.',
      newsletter: true,
      smsUpdates: false,
      language: 'en',
      timezone: 'America/New_York',
      currency: 'USD',
      isVerified: true,
      isActive: true,
    },
    {
      name: 'Mike Johnson',
      firstName: 'Mike',
      lastName: 'Johnson',
      email: 'mike@example.com',
      password: hashSync('password', 10),
      role: 'user',
      bio: 'Tech professional who loves quality clothing and accessories.',
      dateOfBirth: new Date('1988-11-10'),
      phone: '+1-555-0789',
      gender: 'male',
      country: 'Canada',
      state: 'Ontario',
      city: 'Toronto',
      zipCode: 'M5V 3A8',
      website: 'https://mikejohnson.dev',
      linkedIn: 'https://linkedin.com/in/mikejohnson',
      occupation: 'Software Developer',
      company: 'Tech Solutions Ltd.',
      newsletter: false,
      smsUpdates: false,
      language: 'en',
      timezone: 'America/Toronto',
      currency: 'CAD',
      isVerified: false,
      isActive: true,
    },
    {
      name: 'Sarah Wilson',
      firstName: 'Sarah',
      lastName: 'Wilson',
      email: 'sarah@example.com',
      password: hashSync('password', 10),
      role: 'user',
      bio: 'Sustainable fashion blogger and environmental advocate.',
      dateOfBirth: new Date('1995-04-18'),
      phone: '+44-20-7946-0958',
      gender: 'female',
      country: 'United Kingdom',
      state: 'England',
      city: 'London',
      zipCode: 'SW1A 1AA',
      website: 'https://sustainablestyle.blog',
      instagram: 'https://instagram.com/sarahwilson',
      facebook: 'https://facebook.com/sarahwilson',
      occupation: 'Content Creator',
      company: 'Freelance',
      newsletter: true,
      smsUpdates: true,
      language: 'en',
      timezone: 'Europe/London',
      currency: 'GBP',
      isVerified: true,
      isActive: true,
    },
  ],
  products: [
    // Men's Clothing
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort and stretch fabric for all-day wear.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo Ralph Lauren',
      rating: 4.5,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: 'banner-1.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort with non-iron technology.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.90,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 18,
      stock: 12,
      isFeatured: true,
      banner: 'banner-2.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort with wrinkle-resistant fabric.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 31,
      stock: 0,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric for modern professionals.',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.8,
      numReviews: 15,
      stock: 20,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric and button-down collar.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo Ralph Lauren',
      rating: 4.7,
      numReviews: 42,
      stock: 8,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days with premium cotton blend.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo Ralph Lauren',
      rating: 4.6,
      numReviews: 28,
      stock: 14,
      isFeatured: true,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },

    // Women's Clothing
    {
      name: 'Zara Floral Print Midi Dress',
      slug: 'zara-floral-print-midi-dress',
      category: "Women's Dresses",
      description: 'Elegant midi dress with beautiful floral print, perfect for any occasion.',
      images: [
        '/images/sample-products/w1-1.jpg',
        '/images/sample-products/w1-2.jpg',
      ],
      price: 79.90,
      brand: 'Zara',
      rating: 4.4,
      numReviews: 36,
      stock: 18,
      isFeatured: true,
      banner: 'banner-3.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'H&M Sustainable Cotton Blouse',
      slug: 'hm-sustainable-cotton-blouse',
      category: "Women's Tops",
      description: 'Eco-friendly cotton blouse made from sustainable materials.',
      images: [
        '/images/sample-products/w2-1.jpg',
        '/images/sample-products/w2-2.jpg',
      ],
      price: 29.99,
      brand: 'H&M',
      rating: 4.1,
      numReviews: 22,
      stock: 25,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Levi\'s High-Waisted Skinny Jeans',
      slug: 'levis-high-waisted-skinny-jeans',
      category: "Women's Jeans",
      description: 'Classic high-waisted skinny jeans with stretch for comfort and style.',
      images: [
        '/images/sample-products/w3-1.jpg',
        '/images/sample-products/w3-2.jpg',
      ],
      price: 89.50,
      brand: 'Levi\'s',
      rating: 4.8,
      numReviews: 67,
      stock: 30,
      isFeatured: true,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },

    // Accessories
    {
      name: 'Ray-Ban Aviator Classic Sunglasses',
      slug: 'rayban-aviator-classic-sunglasses',
      category: 'Accessories',
      description: 'Iconic aviator sunglasses with premium UV protection and timeless style.',
      images: [
        '/images/sample-products/a1-1.jpg',
        '/images/sample-products/a1-2.jpg',
      ],
      price: 154.00,
      brand: 'Ray-Ban',
      rating: 4.9,
      numReviews: 89,
      stock: 12,
      isFeatured: true,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Nike Air Force 1 Low White',
      slug: 'nike-air-force-1-low-white',
      category: 'Footwear',
      description: 'Classic white leather sneakers with iconic Nike styling and comfort.',
      images: [
        '/images/sample-products/s1-1.jpg',
        '/images/sample-products/s1-2.jpg',
      ],
      price: 110.00,
      brand: 'Nike',
      rating: 4.7,
      numReviews: 156,
      stock: 45,
      isFeatured: true,
      banner: 'banner-4.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Adidas Ultraboost 22 Running Shoes',
      slug: 'adidas-ultraboost-22-running-shoes',
      category: 'Footwear',
      description: 'Premium running shoes with responsive cushioning and energy return.',
      images: [
        '/images/sample-products/s2-1.jpg',
        '/images/sample-products/s2-2.jpg',
      ],
      price: 180.00,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 94,
      stock: 22,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },

    // Electronics/Tech Accessories
    {
      name: 'Apple AirPods Pro (2nd Generation)',
      slug: 'apple-airpods-pro-2nd-generation',
      category: 'Electronics',
      description: 'Premium wireless earbuds with active noise cancellation and spatial audio.',
      images: [
        '/images/sample-products/e1-1.jpg',
        '/images/sample-products/e1-2.jpg',
      ],
      price: 249.00,
      brand: 'Apple',
      rating: 4.8,
      numReviews: 203,
      stock: 35,
      isFeatured: true,
      banner: 'banner-5.jpg',
      createdAt: now,
      updatedAt: now,
    },
    {
      name: 'Samsung Galaxy Watch 6 Classic',
      slug: 'samsung-galaxy-watch-6-classic',
      category: 'Electronics',
      description: 'Advanced smartwatch with health monitoring and premium design.',
      images: [
        '/images/sample-products/e2-1.jpg',
        '/images/sample-products/e2-2.jpg',
      ],
      price: 399.99,
      brand: 'Samsung',
      rating: 4.5,
      numReviews: 78,
      stock: 18,
      isFeatured: false,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },

    // Home & Lifestyle
    {
      name: 'Patagonia Better Sweater Fleece Jacket',
      slug: 'patagonia-better-sweater-fleece-jacket',
      category: 'Outerwear',
      description: 'Sustainable fleece jacket made from recycled polyester with classic styling.',
      images: [
        '/images/sample-products/o1-1.jpg',
        '/images/sample-products/o1-2.jpg',
      ],
      price: 139.00,
      brand: 'Patagonia',
      rating: 4.9,
      numReviews: 127,
      stock: 16,
      isFeatured: true,
      banner: null,
      createdAt: now,
      updatedAt: now,
    },
  ],

  reviews: [
    {
      title: 'Great quality shirt!',
      description: 'Perfect fit and excellent material. Very comfortable for long work days.',
      rating: 5,
      isVerifiedPurchase: true,
      createdAt: new Date('2024-01-15'),
    },
    {
      title: 'Good value for money',
      description: 'Nice shirt but the sizing runs a bit large. Overall satisfied with the purchase.',
      rating: 4,
      isVerifiedPurchase: true,
      createdAt: new Date('2024-01-20'),
    },
    {
      title: 'Excellent dress!',
      description: 'Beautiful floral pattern and great quality fabric. Received many compliments.',
      rating: 5,
      isVerifiedPurchase: true,
      createdAt: new Date('2024-02-01'),
    },
    {
      title: 'Love these jeans',
      description: 'Perfect fit and very comfortable. The high waist is flattering and the stretch is great.',
      rating: 5,
      isVerifiedPurchase: true,
      createdAt: new Date('2024-02-10'),
    },
    {
      title: 'Classic sunglasses',
      description: 'Timeless style and excellent UV protection. Worth the investment.',
      rating: 5,
      isVerifiedPurchase: true,
      createdAt: new Date('2024-02-15'),
    },
  ],
};

export default sampleData;
